### ISSUE TITLE
Sand Oasis To-Do List

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#29]
- [ ] Redo majin travel paths

<h2>Act 1 Environment</h2>

- [x] Fix Stage Culling
- [x] Improve Lighting
- [x] Improve camera jittering during certain turns
- [x] Add completion level demo

<h2>Act 2 Environment</h2>

- [x] Import environment models
- [x] Create paths
- [x] Add cameras
- [x] Add completion level demo
- [x] Add checkpoints

<h2>Act 3 Environment</h2>

- [x] Import environment models
- [x] Create paths
- [x] Add cameras
- [x] Add completion level demo
- [x] Add checkpoints

<h2>Objects</h2>

- [x] Implement Flame shooters
- [x] Finish implementing Sand Scorpion Boss

<h2>Level Maps</h2>

- [x] Go for the Goal
- [x] Diehard Challenge
- [x] Head to Head
- [x] No Pearls
- [x] Special Challenge (Don't break any Jars)
- [x] Diehard Challenge
- [x] Beat the Clock
- [x] Perfect Challenge
- [x] Special Challenge (Break 5 Jars)
- [x] Collect Rings
- [x] Rampage
- [x] Chain of Rings
- [x] Defeat the Boss
