### ISSUE TITLE
Public Release To-Do List

### ISSUE THREAD

**Issue by kumapauz** [Kuma-Boo/project-reignition#60]
<h2>General</h2>

- [x] Implement Shader compilation
- [x] Add menu navigation UI
- [x] Test building/save data
- [x] Implement options menu
- [x] Implement pause menu
- [x] Refactor level lists into custom resources
- [x] Update jump dash trail
- [x] Fix lock-on priority logic
- [x] Fix animation when jumping out of a drift
- [x] Play proper animations in launch rings
- [x] Remake majin hit animation
- [x] Update majin sound effects

<h2>Sand Oasis</h2>

- [x] Add sfx to pillars and spears
- [x] Add vfx to sandfall event
- [x] Fix enemy mapping inconsistencies
- [x] Update vfx of pillars
- [x] Create map for Act 3

<h2>Sand Scorpion</h2>

- [x] Add sfx
- [x] Add vfx
- [x] Create defeat animation
- [x] Add/Improve hit animations
- [x] Improve animation timings
