### ISSUE TITLE
[TODO] SAGE 2024 Tasks

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#68]
This todo list should be completed before the second demo releases. More tasks will be added as needed.

SAND OASIS
-
- [x] Polish collision
- [x] Fix #158
- [x] Fix #78 

DINOSAUR JUNGLE
-
- [x] Update materials
- [x] Improve skybox
- [x] Improve lighting
- [x] Fix Act 3 loading
- [x] Add Act 3 level maps
- [x] Re-implement Majin eggs and Dino eggs
- [x] Improve Flower Majin animations/defeat vfx
- [x] Finish adding camera triggers
- [x] Animate river event
- [x] Animate Dinosaurs
- [x] Add object sfx
- [x] Add object vfx
- [x] Improve Boat collisions
- [x] Fix hazards/speed break rocks
- [x] Fix Spiral Level Culling
- [x] Improve speed break rock shatter effects
- [x] Finish Level Map
- [x] Implement bounce carpets
- [x] Fix homing attack camera
- [x] Add option for camera to sample ahead of the player

GENERAL
- [x] Improve Grindrail controls
- [x] Improve Flying Pot Controls
