### ISSUE TITLE
[TODO] Implement Basic Skills

### ISSUE THREAD

**Issue by Kuma-Boo** [Kuma-Boo/project-reignition#69]
This was originally supposed to be part of the initial demo, but it was delayed to the SAGE 2024 build because it was too much to squeeze in.

- [x] Implement skill equip menu
- [x] Implement Pause Menu skill descriptions
- [x] Implement exp system and leveling
- [x] Implement unlock screen
- [x] Implement skill VFX
- [x] Implement missing animations

**Comment by Kuma-Boo** [comment]
Finished.
